name: NPM Build and Deploy on Master Push
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install dependencies
        run: npm install
      - name: Run build
        run: NODE_OPTIONS="--max-old-space-size=4096" node --max-old-space-size=4096 $(which npm) run build
      - name: Copy build files for nginx to serve
        run: cp -r dist/* /var/www/html/mokzu/
